# Generated by Django 4.0 on 2021-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_object_detection', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'image_storage',
            },
        ),
    ]
