# Generated by Django 4.0 on 2021-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_object_detection', '0003_image_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_storage',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
